@echo off
echo ========================================
echo SenyaMatika - Network Configuration
echo ========================================
echo.

REM Get local IP address
echo Detecting your local IP address...
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set IP=%%a
    goto :found
)

:found
REM Trim spaces
set IP=%IP: =%

REM Check if IP is valid
echo %IP% | findstr /r "^192\.168\." >nul
if %errorlevel% equ 0 goto :valid_ip

echo %IP% | findstr /r "^10\." >nul
if %errorlevel% equ 0 goto :valid_ip

echo %IP% | findstr /r "^172\." >nul
if %errorlevel% equ 0 goto :valid_ip

echo WARNING: Could not detect a valid local network IP!
echo Your IP: %IP%
echo.
echo Please enter your local IP manually:
set /p IP="IP Address: "

:valid_ip
echo.
echo ========================================
echo Configuration Details
echo ========================================
echo.
echo Your Local IP: %IP%
echo Backend URL: http://%IP%:3000/api
echo Health Check: http://%IP%:3000/health
echo.
echo ========================================
echo.

REM Create Flutter configuration file
echo Creating Flutter API configuration...
(
echo // Auto-generated by configure-network.bat
echo // Generated on: %date% %time%
echo.
echo class NetworkConfig {
echo   static const String localIP = '%IP%';
echo   static const String backendUrl = 'http://%IP%:3000/api';
echo   static const String healthUrl = 'http://%IP%:3000/health';
echo }
) > lib\backend\network_config.dart

if exist lib\backend\network_config.dart (
    echo ✓ Created: lib\backend\network_config.dart
) else (
    echo ✗ Failed to create Flutter config file
    echo   Make sure you run this from the project root
)

echo.
echo ========================================
echo Firewall Configuration
echo ========================================
echo.
echo To allow other devices to connect, we need to add a firewall rule.
echo This requires Administrator privileges.
echo.
set /p FIREWALL="Configure firewall now? (Y/N): "

if /i "%FIREWALL%"=="Y" (
    echo.
    echo Adding firewall rule...
    netsh advfirewall firewall delete rule name="SenyaMatika Backend" >nul 2>&1
    netsh advfirewall firewall add rule name="SenyaMatika Backend" dir=in action=allow protocol=TCP localport=3000 >nul 2>&1
    
    if %errorlevel% equ 0 (
        echo ✓ Firewall rule added successfully!
    ) else (
        echo ✗ Failed to add firewall rule
        echo   Please run this script as Administrator
        echo.
        echo   Or manually add the rule:
        echo   1. Open Windows Defender Firewall
        echo   2. Advanced Settings
        echo   3. Inbound Rules ^> New Rule
        echo   4. Port ^> TCP ^> 3000
        echo   5. Allow the connection
    )
) else (
    echo.
    echo Skipping firewall configuration.
    echo You may need to manually allow port 3000 in Windows Firewall.
)

echo.
echo ========================================
echo Testing Backend Connection
echo ========================================
echo.

REM Check if backend is running
echo Testing: http://localhost:3000/health
curl -s http://localhost:3000/health >nul 2>&1

if %errorlevel% equ 0 (
    echo ✓ Backend is running!
    echo.
    echo Testing from network: http://%IP%:3000/health
    curl -s http://%IP%:3000/health >nul 2>&1
    if %errorlevel% equ 0 (
        echo ✓ Backend is accessible from network!
    ) else (
        echo ✗ Backend not accessible from network
        echo   Check firewall settings
    )
) else (
    echo ✗ Backend is not running
    echo.
    echo To start the backend:
    echo   cd backend
    echo   npm start
)

echo.
echo ========================================
echo Configuration Summary
echo ========================================
echo.
echo Local IP: %IP%
echo Backend URL: http://%IP%:3000/api
echo.
echo Files Created:
echo   - lib\backend\network_config.dart
echo.
echo Next Steps:
echo   1. Start backend: cd backend ^&^& npm start
echo   2. Update your Flutter app to use NetworkConfig
echo   3. Test on other devices (same WiFi)
echo.
echo ========================================
echo.

REM Create a quick reference file
(
echo SenyaMatika Network Configuration
echo ================================
echo.
echo Generated: %date% %time%
echo.
echo Local IP: %IP%
echo Backend URL: http://%IP%:3000/api
echo Health Check: http://%IP%:3000/health
echo.
echo Flutter Configuration:
echo   File: lib\backend\network_config.dart
echo   Import: import 'package:senyamatika_math_app/backend/network_config.dart';
echo   Usage: NetworkConfig.backendUrl
echo.
echo Start Backend:
echo   cd backend
echo   npm start
echo.
echo Test Connection:
echo   curl http://%IP%:3000/health
echo.
) > NETWORK_CONFIG.txt

echo Configuration saved to: NETWORK_CONFIG.txt
echo.
pause
