name: senyamatika_math_app
description: "SenyaMatika Mathematics Learning App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  
  # State Management
  provider: ^6.1.1
  
  # UI & Media
  video_player: ^2.5.1
  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  webview_flutter: ^4.4.2
  percent_indicator: ^4.2.3
  
  # Features
  speech_to_text: ^7.3.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  url_launcher: ^6.1.14
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "applogo.png"

flutter:
  uses-material-design: true
  assets:
    - applogo.png
    - assets/assetsmyimage.png
    - assets/images/
    - assets/Videos/
    - assets/DataSet/Numbers/1s/
    - assets/DataSet/Numbers/10s/
    - assets/DataSet/Numbers/100s/
    - assets/DataSet/Numbers/1000s/
    - assets/DataSet/Operators/
    - assets/DataSet/Dictionary/
    - assets/images/fraction.png
    - assets/images/fundamental operations.png
    - assets/images/number values logo.png
    - assets/images/decimal numbers.png
    - assets/images/percentage.png
    - assets/images/mensuration.png
    - assets/images/avatar.png
    - assets/images/child_hello.png
    - assets/gif/sign-language.gif
    - assets/gif/TopicsLogo.gif
    - assets/gif/dictionary.gif
    - assets/gif/to-do-list.gif
    - assets/gif/FirstSign.gif
    - assets/gif/SecondSign.gif
    - assets/gif/ThirdSign.gif
    - assets/images/to-do-list.png
    - assets/images/sign-language.png
    - assets/images/dictionary.png
    - assets/images/topics.png
    - assets/images/menu.png
    - assets/images/applogo.png
    - assets/Videos/Counting.mp4
    - assets/Videos/Compariso.mp4

    
  fonts:
    - family: LondrinaSolid
      fonts:
        - asset: assets/fonts/Londrina Solid Regular.ttf
    - family: LondrinaShadow 
      fonts:
        - asset: assets/fonts/LondrinaShadow-Regular.ttf 
    - family: TitanOne-Regular
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Lora-Regular
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf      