// Auto-generated by configure-network.bat
// Generated on: Sun 03/08/2026 21:24:40.42

class NetworkConfig {
  static const String localIP = '192.168.1.138';
  static const String backendUrl = 'http://192.168.1.138:3000/api';
  static const String healthUrl = 'http://192.168.1.138:3000/health';
}
